project_name: hub-state

before:
  hooks:
    - go mod download

dist: bin

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  filters:
    exclude:
      - "(?i)readme"
      - "(?i)^[typo]{4}"
      - "upd"
      - "GHAW:"
